apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.Name }}-mariadb-pvc"
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.mariadb.persistence.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.mariadb.persistence.size }}"
